### PR TITLE
style: Post show design changes

### PR DESCRIPTION
**Pull request by Mitcheljager**
This PR adjusts the design of show pages in fairly subtle ways. Each section is divided in blocks, with the intend to make it a little more well organized, a little more open, and it looks nice.

## Overall
| Before | After |
| --- | --- |
| image | image |

## Banners
| Before | After |
| --- | --- |
| image | image |

## Without carousel
| Before | After |
| --- | --- |
| image | image |

## No description
| Before | After |
| --- | --- |
| image | image |

## Derivs, expire soon notice
| Before | After |
| --- | --- |
| image | image |

### CODE REVIEW

**Comment by CactusPuppy** [comment]
I think the tab selector block should still be attached to the block below it to make it clear what element the tab selector controls.

**Comment by Mitcheljager** [comment]
@CactusPuppy I see what you mean, but I don't know how I could do this in the current style and still have it look good. I think it's clear enough as is either way.

**Comment by Mitcheljager** [comment]
Inspired by the YouTube video glow thing I've added a glow effect around the carousel based on the average color of the current image.

_The gif does not do it justice, it looks very artifacty here, but that's not actually the case_

carousel-glow

**Comment by CactusPuppy** [comment]
> @CactusPuppy I see what you mean, but I don't know how I could do this in the current style and still have it look good. I think it's clear enough as is either way.

Agreed, seeing it in action makes it look less awkward than it looked at first glance.

**Comment by Mitcheljager** [comment]
@CactusPuppy I ended up changing it a little bit with what you said in mind;

The tabs are now inside of the title block, which is more in line with other pages (namely the profile pages).

image

**Comment by CactusPuppy** [comment]
> @CactusPuppy I ended up changing it a little bit with what you said in mind;
> 
> The tabs are now inside of the title block, which is more in line with other pages (namely the profile pages).
> 
> image

I like this as well. I think my main gripe looking back was the isolation of the tab selection block, which this solves @Mitcheljager

**Comment by Mitcheljager** [comment]
@CactusPuppy I agree, it was a bit much

**Pull request merged**
